### ISSUE TITLE
Is the mod still being developed?

### ISSUE THREAD

**Issue by Xanton19** [BurnhamR/McHeli2#1]
Hello there,
first of all thanks for the attempt to port mcheli to 1.12.2, I have been following this repository very closely for a few months now. I am aware that this repository may not be updated frequently and how complex the mod is. As it is slowly approaching March, I wanted to know if efforts to port this mod have been abandoned or if it is still being actively worked on. Thank you very much for the efforts and have a great day!

-Xanton

**Comment by BurnhamR** [comment]
Hi Xanton, 

We are publishing all main updates on our private repo, for now. We are happy to say we are roughly 75% done with the new mod!
Thanks for your interest, hopefully, we can have it available more soon!

**Comment by Minsit1** [comment]
Hey I'm wondering where I can get in contact with you guys? I have a few questions and am willing to put some money into development and such. @Xanton19 @BurnhamR

**Comment by Xanton19** [comment]
Hi @Minsit1,
thanks for coming by and sharing your interest, but I unfortunately can't help you with development-related questions as I'm not a developer for this project. But I am of course open to help as long as it is within my capabilities. I'm glad to hear that there is interest in this project and I'm also curious about the current status of the project. I can totally understand that this mod porting endeavor is very challenging and lengthy, so I'm actually not surprised that it's still in an unfinished state and taking more time than expected. I really appreciate the efforts @BurnhamR is making to make this complex mod work in relatively modern Minecraft versions.

-Xanton

**Comment by ATank-dev** [comment]
Hello, is the mod still in dev?

**Comment by Raptor22a** [comment]
Half a year later - will a beta release come out any time soon?
